FROM mysql:latest
ENV MYSQL_ROOT_PASSWORD mypassword
ENV MYSQL_DATABASE author_quotes
ENV MYSQL_USER admin1
ENV MYSQL_ROOT_PASSWORD mypassword
ADD dbscript.sql /docker-entrypoint-initdb.d 
EXPOSE 3306